[package]
name = "sty"
version = "0.0.0"
publish = false
description = "Standalone Starlark checker for Bazel sources"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ty_starlark = { workspace = true }
ruff_db = { workspace = true, features = ["os"] }
ruff_source_file = { workspace = true }
ruff_text_size = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
salsa = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
