__all__ = [
    "abs",
    "all",
    "any",
    "bool",
    "dict",
    "dir",
    "enumerate",
    "fail",
    "float",
    "getattr",
    "hasattr",
    "hash",
    "int",
    "len",
    "list",
    "max",
    "min",
    "print",
    "range",
    "repr",
    "reversed",
    "set",
    "sorted",
    "str",
    "tuple",
    "type",
    "zip",
]

class type:
    def __new__(cls, value: object, /) -> str: ...

class _GenericType: ...

class int(_Int):
    @_overload
    def __new__(cls, value: str, /, base: int = 10) -> int: ...
    @_overload
    def __new__(cls, value: int | float | bool, /) -> int: ...

class str(_String):
    def split(self, /, sep: str, maxsplit: int = ...) -> list[str]: ...
    def strip(self, chars: str | None = None, /) -> str: ...

class dict[K, V](_Dict[K, V]):
    @_overload
    def get(self, key: K, /) -> V | None: ...
    @_overload
    def get[D](self, key: K, /, default: D) -> V | D: ...

def sorted[T](
    values: _Iterable[T],
    /,
    key: _Callable[[T], object] | None = None,
    *,
    reverse: bool = False,
) -> list[T]: ...
def fail(
    *args: object, msg: object = None, attr: str | None = None, sep: str = " "
) -> _Never: ...

# Bazel 9's MethodLibrary defines these modes and result containers:
# https://github.com/bazelbuild/bazel/blob/9.0.0/src/main/java/net/starlark/java/eval/MethodLibrary.java
@_overload
def abs(x: int, /) -> int: ...
@_overload
def abs(x: float, /) -> float: ...
def dir(x: object, /) -> list[str]: ...
def enumerate[T](list: _Iterable[T], start: int = 0) -> list[tuple[int, T]]: ...
def getattr(x: object, name: str, default: object = ..., /) -> _Any: ...
def hasattr(x: object, name: str, /) -> bool: ...
def hash(value: str, /) -> int: ...
def print(*args: object, sep: str = " ") -> None: ...
def repr(x: object, /) -> str: ...
def reversed[T](sequence: _Iterable[T], /) -> list[T]: ...
@_overload
def min[T](
    values: _Iterable[T], /, *, key: _Callable[[T], object] | None = None
) -> T: ...
@_overload
def min[T](
    first: T, second: T, /, *rest: T, key: _Callable[[T], object] | None = None
) -> T: ...
@_overload
def max[T](
    values: _Iterable[T], /, *, key: _Callable[[T], object] | None = None
) -> T: ...
@_overload
def max[T](
    first: T, second: T, /, *rest: T, key: _Callable[[T], object] | None = None
) -> T: ...
@_overload
def zip() -> list[tuple[()]]: ...
@_overload
def zip[T](first: _Iterable[T], /) -> list[tuple[T]]: ...
@_overload
def zip[T, U](first: _Iterable[T], second: _Iterable[U], /) -> list[tuple[T, U]]: ...
@_overload
def zip(*args: _Iterable[_Any]) -> list[tuple[_Any, ...]]: ...

# RangeList is immutable; slicing preserves a range rather than making a list.
class range:
    @_overload
    def __new__(cls, stop: int, /) -> range: ...
    @_overload
    def __new__(cls, start: int, stop: int, step: int = 1, /) -> range: ...
    def __iter__(self) -> _Iterator[int]: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, index: int, /) -> int: ...
    @_overload
    def __getitem__(self, index: slice, /) -> range: ...
    def __contains__(self, value: object, /) -> bool: ...
