from collections.abc import (
    Iterable as _Iterable,
    Iterator as _Iterator,
    Sized as _Sized,
)
from typing import (
    Any as _Any,
    Callable as _Callable,
    Never as _Never,
    overload as _overload,
)

class object:
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

class bool:
    def __new__(cls, value: object = False, /) -> bool: ...
    def __lt__(self, other: bool, /) -> bool: ...
    def __le__(self, other: bool, /) -> bool: ...
    def __gt__(self, other: bool, /) -> bool: ...
    def __ge__(self, other: bool, /) -> bool: ...

# Shared helpers use canonical receivers because literal compatibility
# recognizes builtin classes directly instead of traversing their helper bases.
class _Int:
    def __add__(self: int, other: int, /) -> int: ...
    def __sub__(self: int, other: int, /) -> int: ...
    def __mul__(self: int, other: int, /) -> int: ...
    def __truediv__(self: int, other: int, /) -> float: ...
    def __floordiv__(self: int, other: int, /) -> int: ...
    def __mod__(self: int, other: int, /) -> int: ...
    def __and__(self: int, other: int, /) -> int: ...
    def __or__(self: int, other: int, /) -> int: ...
    def __xor__(self: int, other: int, /) -> int: ...
    def __lshift__(self: int, other: int, /) -> int: ...
    def __rshift__(self: int, other: int, /) -> int: ...
    def __pos__(self: int) -> int: ...
    def __neg__(self: int) -> int: ...
    def __invert__(self: int) -> int: ...
    def __lt__(self: int, other: int | float, /) -> bool: ...
    def __le__(self: int, other: int | float, /) -> bool: ...
    def __gt__(self: int, other: int | float, /) -> bool: ...
    def __ge__(self: int, other: int | float, /) -> bool: ...

class float:
    def __new__(cls, value: int | float | bool | str = 0, /) -> float: ...
    def __add__(self, other: int | float, /) -> float: ...
    def __sub__(self, other: int | float, /) -> float: ...
    def __mul__(self, other: int | float, /) -> float: ...
    def __truediv__(self, other: int | float, /) -> float: ...
    def __floordiv__(self, other: int | float, /) -> float: ...
    def __mod__(self, other: int | float, /) -> float: ...
    def __radd__(self, other: int | float, /) -> float: ...
    def __rsub__(self, other: int | float, /) -> float: ...
    def __rmul__(self, other: int | float, /) -> float: ...
    def __rtruediv__(self, other: int | float, /) -> float: ...
    def __rfloordiv__(self, other: int | float, /) -> float: ...
    def __rmod__(self, other: int | float, /) -> float: ...
    def __pos__(self) -> float: ...
    def __neg__(self) -> float: ...
    def __lt__(self, other: int | float, /) -> bool: ...
    def __le__(self, other: int | float, /) -> bool: ...
    def __gt__(self, other: int | float, /) -> bool: ...
    def __ge__(self, other: int | float, /) -> bool: ...

class _String:
    def __new__(cls, value: object, /) -> str: ...
    def __len__(self: str) -> int: ...
    def __getitem__(self: str, index: int | slice, /) -> str: ...
    def __contains__(self: str, value: str, /) -> bool: ...
    def __add__(self: str, other: str, /) -> str: ...
    def __mul__(self: str, count: int, /) -> str: ...
    def __rmul__(self: str, count: int, /) -> str: ...
    def __mod__(self: str, values: object, /) -> str: ...
    def elems(self: str) -> _Iterable[str]: ...
    def upper(self: str) -> str: ...
    def lower(self: str) -> str: ...
    def isupper(self: str) -> bool: ...
    def islower(self: str) -> bool: ...
    def join(self: str, elements: _Iterable[str], /) -> str: ...
    def format(self: str, *args: object, **kwargs: object) -> str: ...
    def startswith(
        self: str,
        prefix: str | tuple[str, ...],
        start: int | None = None,
        end: int | None = None,
        /,
    ) -> bool: ...
    def endswith(
        self: str,
        suffix: str | tuple[str, ...],
        start: int | None = None,
        end: int | None = None,
        /,
    ) -> bool: ...
    def replace(self: str, old: str, new: str, count: int = ..., /) -> str: ...
    def __lt__(self: str, other: str, /) -> bool: ...
    def __le__(self: str, other: str, /) -> bool: ...
    def __gt__(self: str, other: str, /) -> bool: ...
    def __ge__(self: str, other: str, /) -> bool: ...

class slice: ...

class list[T](_GenericType):
    def __init__(self, iterable: _Iterable[T] = (), /) -> None: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, index: int, /) -> T: ...
    @_overload
    def __getitem__(self, index: slice, /) -> list[T]: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __add__(self, other: list[T], /) -> list[T]: ...
    def __mul__(self, count: int, /) -> list[T]: ...
    def __rmul__(self, count: int, /) -> list[T]: ...
    def append(self, value: T, /) -> None: ...
    def extend(self, values: _Iterable[T], /) -> None: ...

class tuple[T](_GenericType):
    def __new__(cls, iterable: _Iterable[T] = (), /) -> tuple[T, ...]: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, index: int, /) -> T: ...
    @_overload
    def __getitem__(self, index: slice, /) -> tuple[T, ...]: ...
    def __contains__(self, value: object, /) -> bool: ...

class _Dict[K, V](_GenericType):
    def __init__(
        self: dict[K, V],
        pairs: dict[K, V] | _Iterable[tuple[K, V]] = (),
        /,
        **kwargs: V,
    ) -> None: ...
    def __iter__(self: dict[K, V]) -> _Iterator[K]: ...
    def __len__(self: dict[K, V]) -> int: ...
    def __getitem__(self: dict[K, V], key: K, /) -> V: ...
    def __setitem__(self: dict[K, V], key: K, value: V, /) -> None: ...
    def __contains__(self: dict[K, V], key: object, /) -> bool: ...
    def __or__[K2, V2](
        self: dict[K, V], other: dict[K2, V2], /
    ) -> dict[K | K2, V | V2]: ...
    def __ror__[K2, V2](
        self: dict[K, V], other: dict[K2, V2], /
    ) -> dict[K | K2, V | V2]: ...
    def keys(self: dict[K, V]) -> list[K]: ...
    def values(self: dict[K, V]) -> list[V]: ...
    def items(self: dict[K, V]) -> list[tuple[K, V]]: ...

class set[T](_GenericType):
    def __init__(self, iterable: _Iterable[T] = (), /) -> None: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    def __contains__(self, value: object, /) -> bool: ...

def any(values: _Iterable[object], /) -> bool: ...
def all(values: _Iterable[object], /) -> bool: ...
def len(value: _Sized, /) -> int: ...
