from collections.abc import (
    Iterable as _Iterable,
    Iterator as _Iterator,
)
from typing import (
    Any as _Any,
    Callable as _Callable,
    Never as _Never,
    overload as _overload,
)

class _Typing:
    Any = _Any
    Never = _Never
    Callable = _Callable
    Iterable = _Iterable

typing: _Typing

__all__ = [
    "all",
    "any",
    "bool",
    "dict",
    "enum",
    "fail",
    "float",
    "int",
    "isinstance",
    "len",
    "list",
    "set",
    "sorted",
    "str",
    "tuple",
    "type",
    "typing",
]

class object:
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

class type:
    def __or__(self, other: object, /) -> object: ...
    def __ror__(self, other: object, /) -> object: ...
    def __new__(cls, value: object, /) -> str: ...

class bool:
    def __new__(cls, value: object = False, /) -> bool: ...
    def __lt__(self, other: bool, /) -> bool: ...
    def __le__(self, other: bool, /) -> bool: ...
    def __gt__(self, other: bool, /) -> bool: ...
    def __ge__(self, other: bool, /) -> bool: ...

class int:
    def __new__(cls, value: int | float | bool | str = 0, /, base: int = 0) -> int: ...
    def __add__(self, other: int, /) -> int: ...
    def __sub__(self, other: int, /) -> int: ...
    def __mul__(self, other: int, /) -> int: ...
    def __truediv__(self, other: int, /) -> float: ...
    def __floordiv__(self, other: int, /) -> int: ...
    def __mod__(self, other: int, /) -> int: ...
    def __and__(self, other: int, /) -> int: ...
    def __or__(self, other: int, /) -> int: ...
    def __xor__(self, other: int, /) -> int: ...
    def __lshift__(self, other: int, /) -> int: ...
    def __rshift__(self, other: int, /) -> int: ...
    def __pos__(self) -> int: ...
    def __neg__(self) -> int: ...
    def __invert__(self) -> int: ...
    def __lt__(self, other: int | float, /) -> bool: ...
    def __le__(self, other: int | float, /) -> bool: ...
    def __gt__(self, other: int | float, /) -> bool: ...
    def __ge__(self, other: int | float, /) -> bool: ...

class float:
    def __new__(cls, value: int | float | bool | str = 0, /) -> float: ...
    def __add__(self, other: int | float, /) -> float: ...
    def __sub__(self, other: int | float, /) -> float: ...
    def __mul__(self, other: int | float, /) -> float: ...
    def __truediv__(self, other: int | float, /) -> float: ...
    def __floordiv__(self, other: int | float, /) -> float: ...
    def __mod__(self, other: int | float, /) -> float: ...
    def __radd__(self, other: int | float, /) -> float: ...
    def __rsub__(self, other: int | float, /) -> float: ...
    def __rmul__(self, other: int | float, /) -> float: ...
    def __rtruediv__(self, other: int | float, /) -> float: ...
    def __rfloordiv__(self, other: int | float, /) -> float: ...
    def __rmod__(self, other: int | float, /) -> float: ...
    def __pos__(self) -> float: ...
    def __neg__(self) -> float: ...
    def __lt__(self, other: int | float, /) -> bool: ...
    def __le__(self, other: int | float, /) -> bool: ...
    def __gt__(self, other: int | float, /) -> bool: ...
    def __ge__(self, other: int | float, /) -> bool: ...

class str:
    def __new__(cls, value: object, /) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int | slice, /) -> str: ...
    def __contains__(self, value: str, /) -> bool: ...
    def __add__(self, other: str, /) -> str: ...
    def __mul__(self, count: int, /) -> str: ...
    def __rmul__(self, count: int, /) -> str: ...
    def __mod__(self, values: object, /) -> str: ...
    def elems(self) -> _Iterable[str]: ...
    def split(
        self, sep: str | None = None, maxsplit: int | None = None, /
    ) -> list[str]: ...
    def strip(self, chars: str = ..., /) -> str: ...
    def upper(self) -> str: ...
    def lower(self) -> str: ...
    def isupper(self) -> bool: ...
    def islower(self) -> bool: ...
    def join(self, elements: _Iterable[str], /) -> str: ...
    def format(self, *args: object, **kwargs: object) -> str: ...
    def startswith(
        self,
        prefix: str | tuple[str, ...],
        start: int | None = None,
        end: int | None = None,
        /,
    ) -> bool: ...
    def endswith(
        self,
        suffix: str | tuple[str, ...],
        start: int | None = None,
        end: int | None = None,
        /,
    ) -> bool: ...
    def replace(self, old: str, new: str, count: int = ..., /) -> str: ...
    def __lt__(self, other: str, /) -> bool: ...
    def __le__(self, other: str, /) -> bool: ...
    def __gt__(self, other: str, /) -> bool: ...
    def __ge__(self, other: str, /) -> bool: ...

class slice: ...

class _GenericType:
    def __class_getitem__(cls, item: object, /) -> object: ...

class list[T](_GenericType):
    def __init__(self, iterable: _Iterable[T] = (), /) -> None: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, index: int, /) -> T: ...
    @_overload
    def __getitem__(self, index: slice, /) -> list[T]: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __add__(self, other: list[T], /) -> list[T]: ...
    def __mul__(self, count: int, /) -> list[T]: ...
    def __rmul__(self, count: int, /) -> list[T]: ...
    def append(self, value: T, /) -> None: ...
    def extend(self, values: _Iterable[T], /) -> None: ...

class tuple[T](_GenericType):
    def __new__(cls, iterable: _Iterable[T] = (), /) -> tuple[T, ...]: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, index: int, /) -> T: ...
    @_overload
    def __getitem__(self, index: slice, /) -> tuple[T, ...]: ...
    def __contains__(self, value: object, /) -> bool: ...

class dict[K, V](_GenericType):
    def __init__(
        self, pairs: dict[K, V] | _Iterable[tuple[K, V]] = (), /, **kwargs: V
    ) -> None: ...
    def __iter__(self) -> _Iterator[K]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: K, /) -> V: ...
    def __setitem__(self, key: K, value: V, /) -> None: ...
    def __contains__(self, key: object, /) -> bool: ...
    def __or__[K2, V2](self, other: dict[K2, V2], /) -> dict[K | K2, V | V2]: ...
    def __ror__[K2, V2](self, other: dict[K2, V2], /) -> dict[K | K2, V | V2]: ...
    @_overload
    def get(self, key: K, /) -> V | None: ...
    @_overload
    def get[D](self, key: K, default: D, /) -> V | D: ...
    def keys(self) -> list[K]: ...
    def values(self) -> list[V]: ...
    def items(self) -> list[tuple[K, V]]: ...

class set[T](_GenericType):
    def __init__(self, iterable: _Iterable[T] = (), /) -> None: ...
    def __iter__(self) -> _Iterator[T]: ...
    def __len__(self) -> int: ...
    def __contains__(self, value: object, /) -> bool: ...

def any(values: _Iterable[object], /) -> bool: ...
def all(values: _Iterable[object], /) -> bool: ...
def len(
    value: str | list[_Any] | tuple[_Any, ...] | dict[_Any, _Any] | set[_Any], /
) -> int: ...
def isinstance(value: object, types: object, /) -> bool: ...
def sorted[T](
    values: _Iterable[T], /, *, key: _Callable[[T], object] = ..., reverse: bool = False
) -> list[T]: ...
def fail(*args: object) -> _Never: ...
def enum(*values: str) -> _Any: ...
