class Any: ...

class _SpecialForm:
    def __or__(self, other: object, /) -> object: ...
    def __ror__(self, other: object, /) -> object: ...

class _Generic: ...

Generic: type[_Generic]
Protocol: _SpecialForm
Callable: _SpecialForm
Literal: _SpecialForm
Never: _SpecialForm

def overload[F](function: F) -> F: ...
