from typing import Protocol

class Iterable[T](Protocol):
    def __iter__(self) -> Iterator[T]: ...

class Iterator[T](Iterable[T], Protocol):
    def __iter__(self) -> Iterator[T]: ...
    def __next__(self) -> T: ...

class Sized(Protocol):
    def __len__(self) -> int: ...
